### PR TITLE
Update strong to skrong

### PR DESCRIPTION
**Pull request by stevendiaz**

### CODE REVIEW

**Comment by rob0rt** [comment]
༼ つ ͠° ͟ ͟ʖ ͡° ༽つ

plz no

**Comment by coltwhaley** [comment]
but like, why

**Comment by rob0rt** [comment]
We play with LANBot.

Omega is rl srs business.

**Comment by aaaanderson** [comment]
bobby ur no fun

**Comment by rainiera** [comment]
Business in the frontend, party in the backend

**Comment by coltwhaley** [comment]
rainier, can we limit our puns to lanbot. thanks, this is srs business

**Comment by arrdem** [comment]
This is asinine. No.

**Comment by rob0rt** [comment]
_thank you based arrdem_

**Comment by arrdem** [comment]
arrdmin lays down the lawz

**Comment by claysmalley** [comment]
[https://www.youtube.com/watch?v=nJNZd6_reas](That's just asinine)

**Comment by claysmalley** [comment]
[That's just asinine](https://www.youtube.com/watch?v=nJNZd6_reas)

**Pull request closed without merging**
